# Generated by Django 3.2.9 on 2021-12-13 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20211212_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='upload_books',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(default='', upload_to='e_books/images')),
                ('detail', models.CharField(max_length=122)),
                ('book', models.FileField(default='', upload_to='e_books/books')),
            ],
        ),
    ]
