# Generated by Django 3.2.9 on 2021-12-13 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_upload_books'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='upload_books',
            new_name='upload_book',
        ),
    ]
